/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WendButtonVariant } from "./components/wend-button/wend-button";
export { WendButtonVariant } from "./components/wend-button/wend-button";
export namespace Components {
    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": WendButtonVariant;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size": string;
    }
}
declare global {
    interface HTMLWendButtonElement extends Components.WendButton, HTMLStencilElement {
    }
    var HTMLWendButtonElement: {
        prototype: HTMLWendButtonElement;
        new (): HTMLWendButtonElement;
    };
    interface HTMLWendIconElement extends Components.WendIcon, HTMLStencilElement {
    }
    var HTMLWendIconElement: {
        prototype: HTMLWendIconElement;
        new (): HTMLWendIconElement;
    };
    interface HTMLElementTagNameMap {
        "wend-button": HTMLWendButtonElement;
        "wend-icon": HTMLWendIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: WendButtonVariant;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size"?: string;
    }

    interface WendButtonAttributes {
        "variant": WendButtonVariant;
        "disabled": boolean;
    }
    interface WendIconAttributes {
        "name": string;
        "size": string;
        "color": string;
    }

    interface IntrinsicElements {
        "wend-button": Omit<WendButton, keyof WendButtonAttributes> & { [K in keyof WendButton & keyof WendButtonAttributes]?: WendButton[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `attr:${K}`]?: WendButtonAttributes[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `prop:${K}`]?: WendButton[K] };
        "wend-icon": Omit<WendIcon, keyof WendIconAttributes> & { [K in keyof WendIcon & keyof WendIconAttributes]?: WendIcon[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `attr:${K}`]?: WendIconAttributes[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `prop:${K}`]?: WendIcon[K] } & OneOf<"name", WendIcon["name"], WendIconAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wend-button": LocalJSX.IntrinsicElements["wend-button"] & JSXBase.HTMLAttributes<HTMLWendButtonElement>;
            "wend-icon": LocalJSX.IntrinsicElements["wend-icon"] & JSXBase.HTMLAttributes<HTMLWendIconElement>;
        }
    }
}
