/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WendButtonVariant } from "./components/wend-button/wend-button";
import { WendHelpTextType } from "./components/wend-help-text/wend-help-text";
import { WendTextInputState } from "./components/wend-text-input/wend-text-input";
export { WendButtonVariant } from "./components/wend-button/wend-button";
export { WendHelpTextType } from "./components/wend-help-text/wend-help-text";
export { WendTextInputState } from "./components/wend-text-input/wend-text-input";
export namespace Components {
    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Name of a wend-ui icon to render on the left of the button label.
         */
        "iconLeft"?: string;
        /**
          * Renders a square, label-less button containing only icon-left. Ignores the label and icon-right.
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Name of a wend-ui icon to render on the right of the button label.
         */
        "iconRight"?: string;
        /**
          * The content of the button. This is required, but can be an empty string for an icon-only button as it will be skipped for icon-only buttons.
          * @default ''
         */
        "label": string;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": WendButtonVariant;
    }
    interface WendCheckbox {
        /**
          * Whether the checkbox is checked.
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled": boolean;
        /**
          * The checkbox's label text. Can be an empty string for a label-less checkbox.
          * @default ''
         */
        "label": string;
    }
    interface WendHelpText {
        /**
          * The help text's message. Can be an empty string to render nothing.
          * @default ''
         */
        "text": string;
        /**
          * Visual tone of the help text.
          * @default 'default'
         */
        "type": WendHelpTextType;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size": string;
    }
    interface WendRadio {
        /**
          * Disables the radio button.
          * @default false
         */
        "disabled": boolean;
        /**
          * The radio button's label text. Can be an empty string for a label-less radio button.
          * @default ''
         */
        "label": string;
        /**
          * Name of the radio group this button belongs to. Radios sharing a name are mutually exclusive.
         */
        "name"?: string;
        /**
          * Whether the radio button is selected.
          * @default false
         */
        "selected": boolean;
        /**
          * Value submitted for this radio button when part of a form.
         */
        "value"?: string;
    }
    interface WendRadioGroup {
        /**
          * Disables every radio in the group.
          * @default false
         */
        "disabled": boolean;
        /**
          * The group's label text. Can be an empty string for a label-less group.
          * @default ''
         */
        "label": string;
        /**
          * Name applied to every wend-radio child, so they act as one mutually-exclusive group.
         */
        "name": string;
        /**
          * Value of the currently selected radio in the group.
         */
        "value"?: string;
    }
    interface WendTextInput {
        /**
          * Disables the input.
          * @default false
         */
        "disabled": boolean;
        /**
          * Supplementary message shown below the input, e.g. a validation message. Can be an empty string to render nothing.
          * @default ''
         */
        "helpText": string;
        /**
          * The input's label text. Can be an empty string for a label-less input.
          * @default ''
         */
        "label": string;
        /**
          * Name submitted for this input when part of a form.
         */
        "name"?: string;
        /**
          * Placeholder text shown when the input is empty.
         */
        "placeholder"?: string;
        /**
          * Marks the input as required. Renders a marker after the label and sets the native `required`/`aria-required` attributes on the input.
          * @default false
         */
        "required": boolean;
        /**
          * Whether the help text is rendered.
          * @default true
         */
        "showHelpText": boolean;
        /**
          * Whether the label is rendered.
          * @default true
         */
        "showLabel": boolean;
        /**
          * Validation state of the input. Drives the field's border color and the help text's tone. The interactive focus ring is handled separately via CSS `:focus-within`, not this prop, so a focused input keeps combining with whichever validation state is already set.
          * @default 'default'
         */
        "state": WendTextInputState;
        /**
          * The input's current text value.
          * @default ''
         */
        "value": string;
    }
    interface WendToggle {
        /**
          * Whether the toggle is on.
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the toggle.
          * @default false
         */
        "disabled": boolean;
    }
}
export interface WendCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendCheckboxElement;
}
export interface WendRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendRadioElement;
}
export interface WendRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendRadioGroupElement;
}
export interface WendTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendTextInputElement;
}
export interface WendToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendToggleElement;
}
declare global {
    interface HTMLWendButtonElement extends Components.WendButton, HTMLStencilElement {
    }
    var HTMLWendButtonElement: {
        prototype: HTMLWendButtonElement;
        new (): HTMLWendButtonElement;
    };
    interface HTMLWendCheckboxElementEventMap {
        "wendChange": boolean;
    }
    interface HTMLWendCheckboxElement extends Components.WendCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendCheckboxElementEventMap>(type: K, listener: (this: HTMLWendCheckboxElement, ev: WendCheckboxCustomEvent<HTMLWendCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendCheckboxElementEventMap>(type: K, listener: (this: HTMLWendCheckboxElement, ev: WendCheckboxCustomEvent<HTMLWendCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendCheckboxElement: {
        prototype: HTMLWendCheckboxElement;
        new (): HTMLWendCheckboxElement;
    };
    interface HTMLWendHelpTextElement extends Components.WendHelpText, HTMLStencilElement {
    }
    var HTMLWendHelpTextElement: {
        prototype: HTMLWendHelpTextElement;
        new (): HTMLWendHelpTextElement;
    };
    interface HTMLWendIconElement extends Components.WendIcon, HTMLStencilElement {
    }
    var HTMLWendIconElement: {
        prototype: HTMLWendIconElement;
        new (): HTMLWendIconElement;
    };
    interface HTMLWendRadioElementEventMap {
        "wendChange": boolean;
    }
    interface HTMLWendRadioElement extends Components.WendRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendRadioElementEventMap>(type: K, listener: (this: HTMLWendRadioElement, ev: WendRadioCustomEvent<HTMLWendRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendRadioElementEventMap>(type: K, listener: (this: HTMLWendRadioElement, ev: WendRadioCustomEvent<HTMLWendRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendRadioElement: {
        prototype: HTMLWendRadioElement;
        new (): HTMLWendRadioElement;
    };
    interface HTMLWendRadioGroupElementEventMap {
        "wendChange": string;
    }
    interface HTMLWendRadioGroupElement extends Components.WendRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendRadioGroupElementEventMap>(type: K, listener: (this: HTMLWendRadioGroupElement, ev: WendRadioGroupCustomEvent<HTMLWendRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendRadioGroupElementEventMap>(type: K, listener: (this: HTMLWendRadioGroupElement, ev: WendRadioGroupCustomEvent<HTMLWendRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendRadioGroupElement: {
        prototype: HTMLWendRadioGroupElement;
        new (): HTMLWendRadioGroupElement;
    };
    interface HTMLWendTextInputElementEventMap {
        "wendChange": string;
    }
    interface HTMLWendTextInputElement extends Components.WendTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendTextInputElementEventMap>(type: K, listener: (this: HTMLWendTextInputElement, ev: WendTextInputCustomEvent<HTMLWendTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendTextInputElementEventMap>(type: K, listener: (this: HTMLWendTextInputElement, ev: WendTextInputCustomEvent<HTMLWendTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendTextInputElement: {
        prototype: HTMLWendTextInputElement;
        new (): HTMLWendTextInputElement;
    };
    interface HTMLWendToggleElementEventMap {
        "wendChange": boolean;
    }
    interface HTMLWendToggleElement extends Components.WendToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendToggleElementEventMap>(type: K, listener: (this: HTMLWendToggleElement, ev: WendToggleCustomEvent<HTMLWendToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendToggleElementEventMap>(type: K, listener: (this: HTMLWendToggleElement, ev: WendToggleCustomEvent<HTMLWendToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendToggleElement: {
        prototype: HTMLWendToggleElement;
        new (): HTMLWendToggleElement;
    };
    interface HTMLElementTagNameMap {
        "wend-button": HTMLWendButtonElement;
        "wend-checkbox": HTMLWendCheckboxElement;
        "wend-help-text": HTMLWendHelpTextElement;
        "wend-icon": HTMLWendIconElement;
        "wend-radio": HTMLWendRadioElement;
        "wend-radio-group": HTMLWendRadioGroupElement;
        "wend-text-input": HTMLWendTextInputElement;
        "wend-toggle": HTMLWendToggleElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Name of a wend-ui icon to render on the left of the button label.
         */
        "iconLeft"?: string;
        /**
          * Renders a square, label-less button containing only icon-left. Ignores the label and icon-right.
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Name of a wend-ui icon to render on the right of the button label.
         */
        "iconRight"?: string;
        /**
          * The content of the button. This is required, but can be an empty string for an icon-only button as it will be skipped for icon-only buttons.
          * @default ''
         */
        "label"?: string;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: WendButtonVariant;
    }
    interface WendCheckbox {
        /**
          * Whether the checkbox is checked.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The checkbox's label text. Can be an empty string for a label-less checkbox.
          * @default ''
         */
        "label"?: string;
        /**
          * Emitted when the checkbox is toggled by the user.
         */
        "onWendChange"?: (event: WendCheckboxCustomEvent<boolean>) => void;
    }
    interface WendHelpText {
        /**
          * The help text's message. Can be an empty string to render nothing.
          * @default ''
         */
        "text"?: string;
        /**
          * Visual tone of the help text.
          * @default 'default'
         */
        "type"?: WendHelpTextType;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size"?: string;
    }
    interface WendRadio {
        /**
          * Disables the radio button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The radio button's label text. Can be an empty string for a label-less radio button.
          * @default ''
         */
        "label"?: string;
        /**
          * Name of the radio group this button belongs to. Radios sharing a name are mutually exclusive.
         */
        "name"?: string;
        /**
          * Emitted when the radio button is selected by the user.
         */
        "onWendChange"?: (event: WendRadioCustomEvent<boolean>) => void;
        /**
          * Whether the radio button is selected.
          * @default false
         */
        "selected"?: boolean;
        /**
          * Value submitted for this radio button when part of a form.
         */
        "value"?: string;
    }
    interface WendRadioGroup {
        /**
          * Disables every radio in the group.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The group's label text. Can be an empty string for a label-less group.
          * @default ''
         */
        "label"?: string;
        /**
          * Name applied to every wend-radio child, so they act as one mutually-exclusive group.
         */
        "name": string;
        /**
          * Emitted when the selected value changes.
         */
        "onWendChange"?: (event: WendRadioGroupCustomEvent<string>) => void;
        /**
          * Value of the currently selected radio in the group.
         */
        "value"?: string;
    }
    interface WendTextInput {
        /**
          * Disables the input.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Supplementary message shown below the input, e.g. a validation message. Can be an empty string to render nothing.
          * @default ''
         */
        "helpText"?: string;
        /**
          * The input's label text. Can be an empty string for a label-less input.
          * @default ''
         */
        "label"?: string;
        /**
          * Name submitted for this input when part of a form.
         */
        "name"?: string;
        /**
          * Emitted as the user types.
         */
        "onWendChange"?: (event: WendTextInputCustomEvent<string>) => void;
        /**
          * Placeholder text shown when the input is empty.
         */
        "placeholder"?: string;
        /**
          * Marks the input as required. Renders a marker after the label and sets the native `required`/`aria-required` attributes on the input.
          * @default false
         */
        "required"?: boolean;
        /**
          * Whether the help text is rendered.
          * @default true
         */
        "showHelpText"?: boolean;
        /**
          * Whether the label is rendered.
          * @default true
         */
        "showLabel"?: boolean;
        /**
          * Validation state of the input. Drives the field's border color and the help text's tone. The interactive focus ring is handled separately via CSS `:focus-within`, not this prop, so a focused input keeps combining with whichever validation state is already set.
          * @default 'default'
         */
        "state"?: WendTextInputState;
        /**
          * The input's current text value.
          * @default ''
         */
        "value"?: string;
    }
    interface WendToggle {
        /**
          * Whether the toggle is on.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the toggle.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the toggle is switched by the user.
         */
        "onWendChange"?: (event: WendToggleCustomEvent<boolean>) => void;
    }

    interface WendButtonAttributes {
        "variant": WendButtonVariant;
        "disabled": boolean;
        "label": string;
        "iconLeft": string;
        "iconRight": string;
        "iconOnly": boolean;
    }
    interface WendCheckboxAttributes {
        "checked": boolean;
        "label": string;
        "disabled": boolean;
    }
    interface WendHelpTextAttributes {
        "text": string;
        "type": WendHelpTextType;
    }
    interface WendIconAttributes {
        "name": string;
        "size": string;
        "color": string;
    }
    interface WendRadioAttributes {
        "selected": boolean;
        "name": string;
        "value": string;
        "label": string;
        "disabled": boolean;
    }
    interface WendRadioGroupAttributes {
        "label": string;
        "name": string;
        "value": string;
        "disabled": boolean;
    }
    interface WendTextInputAttributes {
        "label": string;
        "showLabel": boolean;
        "value": string;
        "placeholder": string;
        "helpText": string;
        "showHelpText": boolean;
        "state": WendTextInputState;
        "disabled": boolean;
        "required": boolean;
        "name": string;
    }
    interface WendToggleAttributes {
        "checked": boolean;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "wend-button": Omit<WendButton, keyof WendButtonAttributes> & { [K in keyof WendButton & keyof WendButtonAttributes]?: WendButton[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `attr:${K}`]?: WendButtonAttributes[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `prop:${K}`]?: WendButton[K] };
        "wend-checkbox": Omit<WendCheckbox, keyof WendCheckboxAttributes> & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes]?: WendCheckbox[K] } & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes as `attr:${K}`]?: WendCheckboxAttributes[K] } & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes as `prop:${K}`]?: WendCheckbox[K] };
        "wend-help-text": Omit<WendHelpText, keyof WendHelpTextAttributes> & { [K in keyof WendHelpText & keyof WendHelpTextAttributes]?: WendHelpText[K] } & { [K in keyof WendHelpText & keyof WendHelpTextAttributes as `attr:${K}`]?: WendHelpTextAttributes[K] } & { [K in keyof WendHelpText & keyof WendHelpTextAttributes as `prop:${K}`]?: WendHelpText[K] };
        "wend-icon": Omit<WendIcon, keyof WendIconAttributes> & { [K in keyof WendIcon & keyof WendIconAttributes]?: WendIcon[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `attr:${K}`]?: WendIconAttributes[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `prop:${K}`]?: WendIcon[K] } & OneOf<"name", WendIcon["name"], WendIconAttributes["name"]>;
        "wend-radio": Omit<WendRadio, keyof WendRadioAttributes> & { [K in keyof WendRadio & keyof WendRadioAttributes]?: WendRadio[K] } & { [K in keyof WendRadio & keyof WendRadioAttributes as `attr:${K}`]?: WendRadioAttributes[K] } & { [K in keyof WendRadio & keyof WendRadioAttributes as `prop:${K}`]?: WendRadio[K] };
        "wend-radio-group": Omit<WendRadioGroup, keyof WendRadioGroupAttributes> & { [K in keyof WendRadioGroup & keyof WendRadioGroupAttributes]?: WendRadioGroup[K] } & { [K in keyof WendRadioGroup & keyof WendRadioGroupAttributes as `attr:${K}`]?: WendRadioGroupAttributes[K] } & { [K in keyof WendRadioGroup & keyof WendRadioGroupAttributes as `prop:${K}`]?: WendRadioGroup[K] } & OneOf<"name", WendRadioGroup["name"], WendRadioGroupAttributes["name"]>;
        "wend-text-input": Omit<WendTextInput, keyof WendTextInputAttributes> & { [K in keyof WendTextInput & keyof WendTextInputAttributes]?: WendTextInput[K] } & { [K in keyof WendTextInput & keyof WendTextInputAttributes as `attr:${K}`]?: WendTextInputAttributes[K] } & { [K in keyof WendTextInput & keyof WendTextInputAttributes as `prop:${K}`]?: WendTextInput[K] };
        "wend-toggle": Omit<WendToggle, keyof WendToggleAttributes> & { [K in keyof WendToggle & keyof WendToggleAttributes]?: WendToggle[K] } & { [K in keyof WendToggle & keyof WendToggleAttributes as `attr:${K}`]?: WendToggleAttributes[K] } & { [K in keyof WendToggle & keyof WendToggleAttributes as `prop:${K}`]?: WendToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wend-button": LocalJSX.IntrinsicElements["wend-button"] & JSXBase.HTMLAttributes<HTMLWendButtonElement>;
            "wend-checkbox": LocalJSX.IntrinsicElements["wend-checkbox"] & JSXBase.HTMLAttributes<HTMLWendCheckboxElement>;
            "wend-help-text": LocalJSX.IntrinsicElements["wend-help-text"] & JSXBase.HTMLAttributes<HTMLWendHelpTextElement>;
            "wend-icon": LocalJSX.IntrinsicElements["wend-icon"] & JSXBase.HTMLAttributes<HTMLWendIconElement>;
            "wend-radio": LocalJSX.IntrinsicElements["wend-radio"] & JSXBase.HTMLAttributes<HTMLWendRadioElement>;
            "wend-radio-group": LocalJSX.IntrinsicElements["wend-radio-group"] & JSXBase.HTMLAttributes<HTMLWendRadioGroupElement>;
            "wend-text-input": LocalJSX.IntrinsicElements["wend-text-input"] & JSXBase.HTMLAttributes<HTMLWendTextInputElement>;
            "wend-toggle": LocalJSX.IntrinsicElements["wend-toggle"] & JSXBase.HTMLAttributes<HTMLWendToggleElement>;
        }
    }
}
