/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WendButtonVariant } from "./components/wend-button/wend-button";
export { WendButtonVariant } from "./components/wend-button/wend-button";
export namespace Components {
    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Name of a wend-ui icon to render on the left of the button label.
         */
        "iconLeft"?: string;
        /**
          * Renders a square, label-less button containing only icon-left. Ignores the label and icon-right.
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Name of a wend-ui icon to render on the right of the button label.
         */
        "iconRight"?: string;
        /**
          * The content of the button. This is required, but can be an empty string for an icon-only button as it will be skipped for icon-only buttons.
          * @default ''
         */
        "label": string;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": WendButtonVariant;
    }
    interface WendCheckbox {
        /**
          * Whether the checkbox is checked.
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled": boolean;
        /**
          * The checkbox's label text. Can be an empty string for a label-less checkbox.
          * @default ''
         */
        "label": string;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size": string;
    }
}
export interface WendCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWendCheckboxElement;
}
declare global {
    interface HTMLWendButtonElement extends Components.WendButton, HTMLStencilElement {
    }
    var HTMLWendButtonElement: {
        prototype: HTMLWendButtonElement;
        new (): HTMLWendButtonElement;
    };
    interface HTMLWendCheckboxElementEventMap {
        "wendChange": boolean;
    }
    interface HTMLWendCheckboxElement extends Components.WendCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWendCheckboxElementEventMap>(type: K, listener: (this: HTMLWendCheckboxElement, ev: WendCheckboxCustomEvent<HTMLWendCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWendCheckboxElementEventMap>(type: K, listener: (this: HTMLWendCheckboxElement, ev: WendCheckboxCustomEvent<HTMLWendCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWendCheckboxElement: {
        prototype: HTMLWendCheckboxElement;
        new (): HTMLWendCheckboxElement;
    };
    interface HTMLWendIconElement extends Components.WendIcon, HTMLStencilElement {
    }
    var HTMLWendIconElement: {
        prototype: HTMLWendIconElement;
        new (): HTMLWendIconElement;
    };
    interface HTMLElementTagNameMap {
        "wend-button": HTMLWendButtonElement;
        "wend-checkbox": HTMLWendCheckboxElement;
        "wend-icon": HTMLWendIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface WendButton {
        /**
          * Disables the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Name of a wend-ui icon to render on the left of the button label.
         */
        "iconLeft"?: string;
        /**
          * Renders a square, label-less button containing only icon-left. Ignores the label and icon-right.
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Name of a wend-ui icon to render on the right of the button label.
         */
        "iconRight"?: string;
        /**
          * The content of the button. This is required, but can be an empty string for an icon-only button as it will be skipped for icon-only buttons.
          * @default ''
         */
        "label"?: string;
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: WendButtonVariant;
    }
    interface WendCheckbox {
        /**
          * Whether the checkbox is checked.
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The checkbox's label text. Can be an empty string for a label-less checkbox.
          * @default ''
         */
        "label"?: string;
        /**
          * Emitted when the checkbox is toggled by the user.
         */
        "onWendChange"?: (event: WendCheckboxCustomEvent<boolean>) => void;
    }
    interface WendIcon {
        /**
          * Icon fill color, as a CSS color.
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Name of the icon to render, matching a name in the wend-ui icons manifest.
         */
        "name": string;
        /**
          * Icon size, as a CSS length.
          * @default '1em'
         */
        "size"?: string;
    }

    interface WendButtonAttributes {
        "variant": WendButtonVariant;
        "disabled": boolean;
        "label": string;
        "iconLeft": string;
        "iconRight": string;
        "iconOnly": boolean;
    }
    interface WendCheckboxAttributes {
        "checked": boolean;
        "label": string;
        "disabled": boolean;
    }
    interface WendIconAttributes {
        "name": string;
        "size": string;
        "color": string;
    }

    interface IntrinsicElements {
        "wend-button": Omit<WendButton, keyof WendButtonAttributes> & { [K in keyof WendButton & keyof WendButtonAttributes]?: WendButton[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `attr:${K}`]?: WendButtonAttributes[K] } & { [K in keyof WendButton & keyof WendButtonAttributes as `prop:${K}`]?: WendButton[K] };
        "wend-checkbox": Omit<WendCheckbox, keyof WendCheckboxAttributes> & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes]?: WendCheckbox[K] } & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes as `attr:${K}`]?: WendCheckboxAttributes[K] } & { [K in keyof WendCheckbox & keyof WendCheckboxAttributes as `prop:${K}`]?: WendCheckbox[K] };
        "wend-icon": Omit<WendIcon, keyof WendIconAttributes> & { [K in keyof WendIcon & keyof WendIconAttributes]?: WendIcon[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `attr:${K}`]?: WendIconAttributes[K] } & { [K in keyof WendIcon & keyof WendIconAttributes as `prop:${K}`]?: WendIcon[K] } & OneOf<"name", WendIcon["name"], WendIconAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wend-button": LocalJSX.IntrinsicElements["wend-button"] & JSXBase.HTMLAttributes<HTMLWendButtonElement>;
            "wend-checkbox": LocalJSX.IntrinsicElements["wend-checkbox"] & JSXBase.HTMLAttributes<HTMLWendCheckboxElement>;
            "wend-icon": LocalJSX.IntrinsicElements["wend-icon"] & JSXBase.HTMLAttributes<HTMLWendIconElement>;
        }
    }
}
