'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendCheckboxCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendCheckbox as WendCheckboxElement, defineCustomElement as defineWendCheckbox } from "@devastudios/web-components/dist/components/wend-checkbox.js";

export type WendCheckboxEvents = { onWendChange: EventName<WendCheckboxCustomEvent<boolean>> };

export const WendCheckbox: StencilReactComponent<WendCheckboxElement, WendCheckboxEvents, Components.WendCheckbox> = /*@__PURE__*/ createComponent<WendCheckboxElement, WendCheckboxEvents, Components.WendCheckbox>({
    tagName: 'wend-checkbox',
    elementClass: WendCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendCheckboxEvents,
    defineCustomElement: defineWendCheckbox
});
