'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendTextAreaCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendTextArea as WendTextAreaElement, defineCustomElement as defineWendTextArea } from "@devastudios/web-components/dist/components/wend-text-area.js";

export type WendTextAreaEvents = { onWendChange: EventName<WendTextAreaCustomEvent<string>> };

export const WendTextArea: StencilReactComponent<WendTextAreaElement, WendTextAreaEvents, Components.WendTextArea> = /*@__PURE__*/ createComponent<WendTextAreaElement, WendTextAreaEvents, Components.WendTextArea>({
    tagName: 'wend-text-area',
    elementClass: WendTextAreaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendTextAreaEvents,
    defineCustomElement: defineWendTextArea
});
