'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendRadioGroupCustomEvent } from "@wend-ui/web-components";
import type { Components } from "@wend-ui/web-components/dist/components";
import { WendRadioGroup as WendRadioGroupElement, defineCustomElement as defineWendRadioGroup } from "@wend-ui/web-components/dist/components/wend-radio-group.js";

export type WendRadioGroupEvents = { onWendChange: EventName<WendRadioGroupCustomEvent<string>> };

export const WendRadioGroup: StencilReactComponent<WendRadioGroupElement, WendRadioGroupEvents, Components.WendRadioGroup, 'name'> = /*@__PURE__*/ createComponent<WendRadioGroupElement, WendRadioGroupEvents, Components.WendRadioGroup, 'name'>({
    tagName: 'wend-radio-group',
    elementClass: WendRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendRadioGroupEvents,
    defineCustomElement: defineWendRadioGroup
});
