'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendOptionCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendOption as WendOptionElement, defineCustomElement as defineWendOption } from "@devastudios/web-components/dist/components/wend-option.js";

export type WendOptionEvents = { onWendChange: EventName<WendOptionCustomEvent<boolean>> };

export const WendOption: StencilReactComponent<WendOptionElement, WendOptionEvents, Components.WendOption, 'value'> = /*@__PURE__*/ createComponent<WendOptionElement, WendOptionEvents, Components.WendOption, 'value'>({
    tagName: 'wend-option',
    elementClass: WendOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendOptionEvents,
    defineCustomElement: defineWendOption
});
