'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendComboBoxCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendComboBox as WendComboBoxElement, defineCustomElement as defineWendComboBox } from "@devastudios/web-components/dist/components/wend-combo-box.js";

export type WendComboBoxEvents = { onWendChange: EventName<WendComboBoxCustomEvent<string[]>> };

export const WendComboBox: StencilReactComponent<WendComboBoxElement, WendComboBoxEvents, Components.WendComboBox> = /*@__PURE__*/ createComponent<WendComboBoxElement, WendComboBoxEvents, Components.WendComboBox>({
    tagName: 'wend-combo-box',
    elementClass: WendComboBoxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendComboBoxEvents,
    defineCustomElement: defineWendComboBox
});
