'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@wend-ui/web-components/dist/components";
import { WendIcon as WendIconElement, defineCustomElement as defineWendIcon } from "@wend-ui/web-components/dist/components/wend-icon.js";

export type WendIconEvents = NonNullable<unknown>;

export const WendIcon: StencilReactComponent<WendIconElement, WendIconEvents, Components.WendIcon, 'name'> = /*@__PURE__*/ createComponent<WendIconElement, WendIconEvents, Components.WendIcon, 'name'>({
    tagName: 'wend-icon',
    elementClass: WendIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as WendIconEvents,
    defineCustomElement: defineWendIcon
});
