'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendSelectCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendSelect as WendSelectElement, defineCustomElement as defineWendSelect } from "@devastudios/web-components/dist/components/wend-select.js";

export type WendSelectEvents = { onWendChange: EventName<WendSelectCustomEvent<string>> };

export const WendSelect: StencilReactComponent<WendSelectElement, WendSelectEvents, Components.WendSelect> = /*@__PURE__*/ createComponent<WendSelectElement, WendSelectEvents, Components.WendSelect>({
    tagName: 'wend-select',
    elementClass: WendSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendSelectEvents,
    defineCustomElement: defineWendSelect
});
