'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@devastudios/web-components/dist/components";
import { WendHelpText as WendHelpTextElement, defineCustomElement as defineWendHelpText } from "@devastudios/web-components/dist/components/wend-help-text.js";

export type WendHelpTextEvents = NonNullable<unknown>;

export const WendHelpText: StencilReactComponent<WendHelpTextElement, WendHelpTextEvents, Components.WendHelpText> = /*@__PURE__*/ createComponent<WendHelpTextElement, WendHelpTextEvents, Components.WendHelpText>({
    tagName: 'wend-help-text',
    elementClass: WendHelpTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as WendHelpTextEvents,
    defineCustomElement: defineWendHelpText
});
