'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendChipCustomEvent } from "@devastudios/web-components";
import type { Components } from "@devastudios/web-components/dist/components";
import { WendChip as WendChipElement, defineCustomElement as defineWendChip } from "@devastudios/web-components/dist/components/wend-chip.js";

export type WendChipEvents = { onWendClose: EventName<WendChipCustomEvent<void>> };

export const WendChip: StencilReactComponent<WendChipElement, WendChipEvents, Components.WendChip> = /*@__PURE__*/ createComponent<WendChipElement, WendChipEvents, Components.WendChip>({
    tagName: 'wend-chip',
    elementClass: WendChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendClose: 'wendClose' } as WendChipEvents,
    defineCustomElement: defineWendChip
});
