'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendToggleCustomEvent } from "@wend-ui/web-components";
import type { Components } from "@wend-ui/web-components/dist/components";
import { WendToggle as WendToggleElement, defineCustomElement as defineWendToggle } from "@wend-ui/web-components/dist/components/wend-toggle.js";

export type WendToggleEvents = { onWendChange: EventName<WendToggleCustomEvent<boolean>> };

export const WendToggle: StencilReactComponent<WendToggleElement, WendToggleEvents, Components.WendToggle> = /*@__PURE__*/ createComponent<WendToggleElement, WendToggleEvents, Components.WendToggle>({
    tagName: 'wend-toggle',
    elementClass: WendToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendToggleEvents,
    defineCustomElement: defineWendToggle
});
