'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendRadioCustomEvent } from "@wend-ui/web-components";
import type { Components } from "@wend-ui/web-components/dist/components";
import { WendRadio as WendRadioElement, defineCustomElement as defineWendRadio } from "@wend-ui/web-components/dist/components/wend-radio.js";

export type WendRadioEvents = { onWendChange: EventName<WendRadioCustomEvent<boolean>> };

export const WendRadio: StencilReactComponent<WendRadioElement, WendRadioEvents, Components.WendRadio> = /*@__PURE__*/ createComponent<WendRadioElement, WendRadioEvents, Components.WendRadio>({
    tagName: 'wend-radio',
    elementClass: WendRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendRadioEvents,
    defineCustomElement: defineWendRadio
});
