'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type WendTextInputCustomEvent } from "@wend-ui/web-components";
import type { Components } from "@wend-ui/web-components/dist/components";
import { WendTextInput as WendTextInputElement, defineCustomElement as defineWendTextInput } from "@wend-ui/web-components/dist/components/wend-text-input.js";

export type WendTextInputEvents = { onWendChange: EventName<WendTextInputCustomEvent<string>> };

export const WendTextInput: StencilReactComponent<WendTextInputElement, WendTextInputEvents, Components.WendTextInput> = /*@__PURE__*/ createComponent<WendTextInputElement, WendTextInputEvents, Components.WendTextInput>({
    tagName: 'wend-text-input',
    elementClass: WendTextInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWendChange: 'wendChange' } as WendTextInputEvents,
    defineCustomElement: defineWendTextInput
});
